### ISSUE TITLE
스터디:LSTM:11.1:순환벡터와 기울기 정보의 소멸 및 폭주

### ISSUE THREAD

**Issue by eubinecto** [eubinecto/k4ji_ai#8]
## 순환 계층 소멸 및 폭주 문제의 대안 및 해결책

**Comment by eubinecto** [comment]
LSTM을 공부를 함에 있어, 나는 크게 다음의 3가지 질문에 대한 명료한 답을 얻고 싶다.
1. LSTM이란 무엇인가?
2.LSTM은 어떤 문제를 해결하기 위해 고안된 모델인가?
3. 그래서 LSTM은 어떻게 동작하는가?

이 소단원은 내가 볼 때, 두번째 질문에 대한 답을 얻을 수 있는 부분인 것으로 보임.

RNN에서 gradient vanishing & exploding 이라는 문제가 있기 때문에, 그것을 해결하기 위해 고안된 것이 LSTM인 것이 아닐까?

일단 현재로서는 그렇게 생각한다. 이런 생각을 가지고 공부를 해보고, 이 생각에 뭔가 잘못된 것이 있거나, 추가해야할 것이 있다면 천천히 수정해나가보도록 하자.

**Comment by eubinecto** [comment]
아, 시작부터 책을 읽기는 귀찮다. 

일단 웹 검색을 해보면서 대충 어떤 내용인지 감을 잡고, 그 다음에 책을 읽으면서 생각을 정리해보자.

**Comment by eubinecto** [comment]
16th of August, 2020
## vanishing & exploding gradient 문제는 왜 유독 RNN에서 심한걸까? 

> (pg 490) ... 이 문제는 딥러닝 신경망이 깊어저 점점 많은 계층을 갖게 될수록 더 심각해졌다.

층이 깊은 DNN이라면, RNN과 마찬가지로,  backprogation으로 웨이트가 학습될 때, RNN과 마찬가지로 vanishing & exploding gradient 문제가 나타난다. 

> (pg 491) ... 문제를 일으킬 소지가 있는 특정 데이터와 혼합해 처리하면서 많이 완화... 편미분을 이용한 손실 기울기 계산과정을 정확히 이해하고 적용... 손실 기울기의 소멸 및 폭주 현상 자체가 그다지 심각한 문제로 거론되지는 않는다... 

그렇게 이 두 문제가 DNN에서는 어느정도 해결된 문제라면, 왜 RNN에서는

**Comment by eubinecto** [comment]
## LSTM이란?

**Comment by eubinecto** [comment]
## 깊은 신경망에서의 vanishing & exploding gradient 문제

**Comment by eubinecto** [comment]
## 깊은 신경망에서의 vanishing & exploding gradient 문제 해소

- batch normalisation  <- 두 문제를 해결하는데에 큰 도움이 되었음.

funfact: 배치 정규화 이전에 나온 VGG16, VGG19는 층이 너무 깊어서 unstable gradient로 인해 수렴하지가 않았음. 그래서 11층까지만 쌓고 그 레이어만 가지고 우선적으로 학습시킨 다음, 어느정도 수렴했을 때 레이어를 더 추가하는 식으로 훈련을 진행했다고 함.

**Comment by eubinecto** [comment]
## 순환 신경망에서는 유독 심하다

**Comment by eubinecto** [comment]
## 순환 벡터 원소 값의 소멸 및 폭주 문제

**Comment by eubinecto** [comment]
## 순환 계층 순전파 과정과 역전파 과정에서의 소멸 및 폭주 문제

**Comment by eubinecto** [comment]
## 순환 계층 소멸 및 폭주 문제의 심각성

**Comment by eubinecto** [comment]
## 순환 계층 소멸 및 폭주 문제의 대안 및 해결책

- LSTM to the rescue.

**Comment by JinYeJin** [comment]
p.491 "문제를 일으킬 소지가 있는 특정 데이터를 다른 데이터와 혼합해 처리" 부분에 대한 코멘트인데요.

[Batch Normalization: Accelerating Deep Network Training by Reducing Internal Covariate Shift](https://arxiv.org/pdf/1502.03167.pdf)
[위 논문의 한국어 정리](http://sanghyukchun.github.io/88/)

이 논문에 기반해서 나온 얘기인 것 같은데 맥락은 이해가 가지만 여전히 "문제를 일으킬 소지가 있는 특정 데이터를 다른 데이터와 혼합해 처리"라는 표현은 잘 모르겠네요.
